// swift-tools-version:5.9
import PackageDescription

// Local Swift package wrapping the `crates/ffi` UniFFI bridge (Plan 07 Task 9).
//
// Layout:
//   Frameworks/ffiFFI.xcframework  — GITIGNORED. Regenerate with
//                                    `apps/ios/build-ffi.sh` (device + sim
//                                    static-lib slices built from
//                                    `crates/ffi` via `crates/ffi/README.md`).
//   Sources/MurmurCoreFFI/ffi.swift — generated by `uniffi-bindgen`; COMMITTED
//                                    (matches the checked-in Rust surface;
//                                    regenerated by the same build script
//                                    whenever the FFI surface changes).
//
// `ffiFFI` (binaryTarget) is the raw C symbols + module map from the Rust
// staticlib; `MurmurCoreFFI` is the Swift-facing target the app imports.
let package = Package(
    name: "MurmurCoreFFI",
    platforms: [.iOS(.v17)],
    products: [
        .library(name: "MurmurCoreFFI", targets: ["MurmurCoreFFI"])
    ],
    targets: [
        .binaryTarget(
            name: "ffiFFI",
            path: "Frameworks/ffiFFI.xcframework"
        ),
        .target(
            name: "MurmurCoreFFI",
            dependencies: ["ffiFFI"],
            path: "Sources/MurmurCoreFFI",
            // The `ffiFFI` static lib is built WITH the `whisper` feature
            // (build-ffi.sh), which vendors whisper.cpp + ggml (C++) and its
            // Metal/Accelerate backends. Those objects reference the C++ runtime
            // (___cxa_*, std::__throw_*) and the Metal/MetalKit/Accelerate
            // frameworks; the app target must link them or the final link fails
            // with "symbol(s) not found for architecture arm64". rustc passes
            // these on its own cross-link, but Xcode linking the .a does not —
            // so the FFI package declares them here for every consumer.
            linkerSettings: [
                .linkedLibrary("c++"),
                .linkedFramework("Metal"),
                .linkedFramework("MetalKit"),
                .linkedFramework("Foundation"),
                .linkedFramework("Accelerate")
            ]
        )
    ]
)
